---
- name: Directorio de configuración existe
  become: true
  file:
    path: "/etc/rancher/k3s"
    state: directory
    owner: root
    group: root

- name: Copiar archivo de configuración
  become: true
  template:
    src: "config.yaml.j2"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: root
    group: root
    mode: 0544

- name: Copiar servicio
  register: k3s_service
  become: true
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Directorio de servidor existe
  become: true
  file:
    path: /var/lib/rancher/k3s/server
    state: directory
    owner: root
    group: root

- name: Subir archivo de token
  become: true
  copy:
    src: "{{ k3s_cluster_local_path }}/server-token"
    dest: /var/lib/rancher/k3s/server/token


# FIXME: Tiene que haber otra forma más confiable
# Necesitamos asegurarnos de que los nodos anteriores ya están inicializados
# antes de poder conectar más nodos. El servicio k3s puede fallar al arrancar.
- name: Esperar a que el nodo se registre
  wait_for:
    timeout: 10
  delegate_to: localhost

- name: Activar/reiniciar el servicio
  become: true
  loop_control:
    pause: 20
  systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
