---
- name: Directorio de configuración existe
  become: true
  file:
    path: "/etc/rancher/k3s"
    state: directory
    owner: root
    group: root

- name: Copiar archivo de configuración
  become: true
  template:
    src: "config.yaml.j2"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: root
    group: root
    mode: 0544

- name: Copiar servicio
  register: k3s_service
  become: true
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Directorio de servidor existe
  become: true
  file:
    path: /var/lib/rancher/k3s/server
    state: directory
    owner: root
    group: root

- name: Subir archivo de token
  become: true
  copy:
    src: "{{ k3s_cluster_local_path }}/node-token"
    dest: /var/lib/rancher/k3s/server/node-token

- name: Activar/reiniciar el servicio
  become: true
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
