---

- hosts: k3s_nodes
  roles:
    - role: prereq
    - role: download

- hosts: k3s_pi
  - role: raspberrypi

- hosts: k3s_master[0]
  roles:
    - k3s-ansible/roles/k3s/master

- hosts: k3s_master[1:]
  roles:
    - k3s-ansible/roles/k3s/master-join

- hosts: k3s_agents
  roles:
    - k3s-ansible/roles/k3s/agent
