---
- name: Directorio de configuración existe
  become: true
  file:
    path: "/etc/rancher/k3s"
    state: directory
    owner: root
    group: root

- name: Copiar archivo de configuración
  become: true
  template:
    src: "config.yml.j2"
    dest: "/etc/rancher/k3s/config.yml"
    owner: root
    group: root
    mode: 0544

- name: Copiar servicio
  register: k3s_service
  become: true
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Activar/reiniciar el servicio
  become: true
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Esperar por el token
  become: true
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Descargar archivo de token
  become: true
  fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: "files/keys/{{ inventory_hostname }}/"
    flat: yes

- name: Directorio ~/.kube existe
  file:
    path: ~{{ ansible_user }}/.kube/
    state: directory
    mode: "u=rwx,g=rx,o="
  register: kube

- name: Copiar configuración en ~/.kube
  become: true
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Crear alias kubectl -> k3s
  become: true
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Crear alias crictl -> k3s
  become: true
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
