---
- name: Directorio para el token existe
  become: true
  file:
    path: /var/lib/rancher/k3s/server
    state: directory

- name: Subir archivo de token
  become: true
  copy:
    src: "files/keys/{{ master_hostname }}/node-token"
    dest: /var/lib/rancher/k3s/server/node-token

- name: Copiar archivo de configuración
  become: true
  template:
    src: "config.yml.j2"
    dest: "/etc/rancher/k3s/config.yml"
    owner: root
    group: root
    mode: 0544

- name: Copiar servicio
  become: true
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Activar/reiniciar el servicio
  become: true
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
